### ISSUE TITLE
[環境構築] CI/CDパイプラインの構築

### ISSUE THREAD

**Issue by YukihiroArakawa** [YukihiroArakawa/search_circle_app#39]
### 作業フロー
1. circle ciのデモが動く
2. circle ciを自分の環境の設定でビルドできる
3. テストが動かせる
4. 自動デプロイができる

**Comment by YukihiroArakawa** [comment]
## 作業 1 : circle ciのデモが動く
```
version: 2.1
jobs:
    build:
      docker: 
        - image: circleci/node:4.8.2 # ジョブのコマンドが実行されるプライマリ コンテナ
      steps:
        - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
        - run: echo "hello world" # `echo` コマンドを実行します
        - run: echo "hello world" # `echo` コマンドを実行します
        - run: echo "hello world" # `echo` コマンドを実行します
```
